spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:querydb
    password: pwd
    username: user
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database: h2
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  task:
    scheduling:
      pool:
        size: 1
      thread-name-prefix: query-poller
    execution:
      thread-name-prefix: async-query-measure
      pool:
        core-size: 8
        max-size: 8
        queue-capacity: 1024
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
    com:
      zaxxer:
        hikari: DEBUG

poller:
  fixed-delay: 10000

db:
  drivers:
    mssql: com.microsoft.sqlserver.jdbc.SQLServerDriver
    postgresql: org.postgresql.Driver
    h2: org.h2.Driver
    mysql: com.mysql.cj.jdbc.Driver
  remotes:
    db_h2:
      jdbcUrl: jdbc:h2:mem:INFORMATION_SCHEMA
      driver-class-name: ${db.drivers.h2}
      password: pwd
      username: user
      maximum-pool-size: 1
      poolName: info-db-pool

    db_mssql:
      jdbcUrl: jdbc:sqlserver://localhost:1433;DatabaseName=db_mssql
      driver-class-name: ${db.drivers.mssql}
      password: pwd
      username: sa
      maximum-pool-size: 1
      poolName: integration-db-pool

    db_mssql_2:
      jdbcUrl: jdbc:sqlserver://localhost:1434;DatabaseName=db_mssql2
      driver-class-name: ${db.drivers.mssql}
      password: pwd
      username: sa
      maximum-pool-size: 1
      poolName: event-food-db-pool

server:
  port: 8081
