spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      pool-name: "local-pool"
    driver-class-name: ${db.drivers.postgresql}
    url: jdbc:postgresql://postgres-querydb:5432/querydb
    password: pwd
    username: postgres
  jpa:
    database: postgresql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  task:
    scheduling:
      pool:
        size: 1
      thread-name-prefix: query-poller
    execution:
      thread-name-prefix: async-query-measure
      pool:
        core-size: 4
        max-size: 4
        queue-capacity: 1024
poller:
  fixed-delay: 10000

db:
  drivers:
    mssql: com.microsoft.sqlserver.jdbc.SQLServerDriver
    postgresql: org.postgresql.Driver
    h2: org.h2.Driver
    mysql: com.mysql.cj.jdbc.Driver

server:
  port: 8081
